package com.casterlabs.greenmart.model.endusers;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import com.casterlabs.greenmart.Services.CustomerLocationTypeConverter;

@DynamoDBTable(tableName = "CustomerInfo")
public class CustomerInfo {

    private String customerId;
    private String customerName;
    private String customerAge;
    private CustomerLocation customerLocation;
    private String customerAddress;
    private String customerTelephone1;
    private String customerTelephone2;
    private String customerStatus;
    private String customerPassword;

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    public String getCustomerId() {
        return customerId;
    }

    public void setCustomerId(String customerId) {
        this.customerId = customerId;
    }

    @DynamoDBAttribute
    public String getCustomerName() {
        return customerName;
    }

    public void setCustomerName(String customerName) {
        this.customerName = customerName;
    }

    @DynamoDBAttribute
    public String getCustomerAge() {
        return customerAge;
    }

    public void setCustomerAge(String customerAge) {
        this.customerAge = customerAge;
    }

    @DynamoDBTypeConverted(converter = CustomerLocationTypeConverter.class)
    @DynamoDBAttribute
    public CustomerLocation getCustomerLocation() {
        return customerLocation;
    }

    public void setCustomerLocation(CustomerLocation customerLocation) {
        this.customerLocation = customerLocation;
    }

    @DynamoDBAttribute
    public String getCustomerAddress() {
        return customerAddress;
    }

    public void setCustomerAddress(String customerAddress) {
        this.customerAddress = customerAddress;
    }

    @DynamoDBAttribute
    public String getCustomerTelephone1() {
        return customerTelephone1;
    }

    public void setCustomerTelephone1(String customerTelephone1) {
        this.customerTelephone1 = customerTelephone1;
    }

    @DynamoDBAttribute
    public String getCustomerTelephone2() {
        return customerTelephone2;
    }

    public void setCustomerTelephone2(String customerTelephone2) {
        this.customerTelephone2 = customerTelephone2;
    }

    @DynamoDBAttribute
    public String getCustomerStatus() {
        return customerStatus;
    }

    public void setCustomerStatus(String customerStatus) {
        this.customerStatus = customerStatus;
    }

    @DynamoDBAttribute
    public String getCustomerPassword() {
        return customerPassword;
    }

    public void setCustomerPassword(String customerPassword) {
        this.customerPassword = customerPassword;
    }
}
