package com.casterlabs.greenmart.model.endusers;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "CustomerCartItems")
public class CustomerCartItems {

    private String cartItemId;
    private String customerId;
    private String productId;
    private String productStatus;
    private Integer productQuantity;
    private String productDeliveryDate;
    private String transactionStatus;

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    public String getCartItemId() {
        return cartItemId;
    }

    public void setCartItemId(String cartItemId) {
        this.cartItemId = cartItemId;
    }

    @DynamoDBAttribute
    public String getCustomerId() {
        return customerId;
    }

    public void setCustomerId(String customerId) {
        this.customerId = customerId;
    }

    @DynamoDBAttribute
    public String getProductId() {
        return productId;
    }

    public void setProductId(String productId) {
        this.productId = productId;
    }

    @DynamoDBAttribute
    public String getProductStatus() {
        return productStatus;
    }

    public void setProductStatus(String productStatus) {
        this.productStatus = productStatus;
    }

    @DynamoDBAttribute
    public String getTransactionStatus() {
        return transactionStatus;
    }

    public void setTransactionStatus(String transactionStatus) {
        this.transactionStatus = transactionStatus;
    }

    @DynamoDBAttribute
    public Integer getProductQuantity() {
        return productQuantity;
    }

    public void setProductQuantity(Integer productQuantity) {
        this.productQuantity = productQuantity;
    }

    @DynamoDBAttribute
    public String getProductDeliveryDate() {
        return productDeliveryDate;
    }

    public void setProductDeliveryDate(String productDeliveryDate) {
        this.productDeliveryDate = productDeliveryDate;
    }
}
